# Conclusion

This project could be a great start to something even more meaningful. Sephora provides much more information than we have used in this project. 
Besides basic information of a product, Sephora also provides its ingredient list, suitable skin type, and much more. We could also relate the discussion of top rated brands to the style of product design the brand uses as to what are the main ingredients, what are the main target of skin types and etc. Nowadays, more and more brands market towards the use of "clean" ingredients in their products, and to see if choice of ingredients speak to customers would be an interesting extention to this project. Sephora also asks customers to provide detailed information such as skin color, skin type, eye color, concerns, and etc when writing reviews. These customer profiling information along could be used to analyze what types of products or brands fit certain types of customers with specific concerns and characteristics. This project also has application in machine learning: given some customer profiles and product information, could we predict the performance of certain products? It is certainly exciting to work with real life data, and we believe we could certainly dig even further with the tools we have.

If you wish to re-create our project, see the Github repo here for data and everything else: https://github.com/yujie980201/Sephora
<br>
*All colors used in this project are colorblind friendly.